global:
  environment: production-gcp

frontend:
  replicaCount: 3
  image:
    repository: gcr.io/<your-project-id>/todo-frontend
    tag: "prod"
  service:
    type: LoadBalancer

backend:
  replicaCount: 3
  image:
    repository: gcr.io/<your-project-id>/todo-backend
    tag: "prod"

notificationService:
  replicaCount: 2
  image:
    repository: gcr.io/<your-project-id>/notification-service
    tag: "prod"

recurringTaskService:
  replicaCount: 2
  image:
    repository: gcr.io/<your-project-id>/recurring-task-service
    tag: "prod"

kafka:
  brokers: "taskflow-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
